import{catalog}from'../data/filmes.js';
const S={page:'home',q:'',cat:'Todos',list:JSON.parse(localStorage.onixList||'[]'),watched:+(localStorage.onixWatched||0),id:null};
const cats=['Todos','Ação','Comédia','Drama','Anime','Suspense','Aventura','Ficção científica'],A=document.querySelector('#app');
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const item=id=>catalog.find(x=>x.id===id);
function card(x){return`<article class="card"><button class="poster" data-open="${x.id}"><img src="${x.poster}" alt="" loading="lazy"><i>${x.rating}</i></button><b>${esc(x.title)}</b><small>${x.year} • ${esc(x.category)}</small></article>`}
function nav(p,ic,t){return`<button class="${S.page===p?'on':''}" data-page="${p}"><strong>${ic}</strong>${t}</button>`}
function frame(c){A.innerHTML=`<div class="shell"><header><a class="logo" data-page="home">ONIX</a><button data-page="search">⌕</button></header><main>${c}</main><nav>${nav('home','⌂','Início')}${nav('movies','▣','Filmes')}${nav('series','▤','Séries')}${nav('list','♡','Lista')}${nav('profile','♙','Perfil')}</nav></div>`;bind()}
function home(){let x=catalog[0];return`<section class="hero"><div><em>DESTAQUE</em><h1>${esc(x.title)}</h1><p>${esc(x.description)}</p><button class="primary" data-watch="${x.id}">▶ Assistir</button><button class="secondary" data-add="${x.id}">＋ Lista</button></div></section><h2>Em alta</h2><div class="rail">${catalog.slice(0,5).map(card).join('')}</div><h2>Categorias</h2><div class="chips">${cats.map(c=>`<button data-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div>`}
function listing(type,title){let a=catalog.filter(x=>x.type===type);if(S.cat!=='Todos')a=a.filter(x=>x.category===S.cat);return`<div class="head"><h1>${title}</h1><select id="cat">${cats.map(c=>`<option ${S.cat===c?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="grid">${a.map(card).join('')||'<p class="empty">Nada encontrado.</p>'}</div>`}
function search(){let a=catalog.filter(x=>(x.title+' '+x.category).toLowerCase().includes(S.q.toLowerCase()));return`<h1>Pesquisar</h1><input id="q" class="input" value="${esc(S.q)}" placeholder="Pesquisar..."><div class="grid">${a.map(card).join('')}</div>`}
function detail(x){return`<button data-page="home" class="back">← Voltar</button><div class="detail"><img src="${x.poster}" alt=""><div><em>${esc(x.category)}</em><h1>${esc(x.title)}</h1><p>${x.year} • ${x.rating}/10</p><p>${esc(x.description)}</p><button class="primary" data-watch="${x.id}">▶ Assistir agora</button><button class="secondary" data-add="${x.id}">＋ Lista</button><button class="secondary" data-share="${x.id}">↗ Partilhar</button></div></div><h2>Recomendados</h2><div class="rail">${catalog.filter(y=>y.id!==x.id).slice(0,4).map(card).join('')}</div>`}
function player(x){return`<button data-page="home" class="back">← Voltar</button><video controls playsinline poster="${x.poster}" src="${x.video}"></video><h1>${esc(x.title)}</h1><p class="muted">Vídeo de demonstração. Use apenas mídia que você tenha autorização para distribuir.</p>`}
function profile(){return`<div class="profile"><div class="avatar">👤</div><h1>Meu perfil</h1><p>Utilizador ONIX</p></div><div class="stats"><div><b>${S.list.length}</b><small>Na lista</small></div><div><b>${S.watched}</b><small>Assistidos</small></div></div>`}
function render(){let c=S.page==='home'?home():S.page==='movies'?listing('filme','Filmes'):S.page==='series'?listing('serie','Séries'):S.page==='search'?search():S.page==='list'?`<h1>Minha lista</h1><div class="grid">${S.list.map(item).filter(Boolean).map(card).join('')||'<p class="empty">Lista vazia.</p>'}</div>`:S.page==='profile'?profile():S.page==='detail'?detail(item(S.id)):player(item(S.id));frame(c)}
function bind(){document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{S.page=x.dataset.page;render()});document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>{S.id=x.dataset.open;S.page='detail';render()});document.querySelectorAll('[data-watch]').forEach(x=>x.onclick=()=>{S.id=x.dataset.watch;S.watched++;localStorage.onixWatched=S.watched;S.page='player';render()});document.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>{S.list=S.list.includes(x.dataset.add)?S.list.filter(i=>i!==x.dataset.add):[...S.list,x.dataset.add];localStorage.onixList=JSON.stringify(S.list);render()});document.querySelectorAll('[data-share]').forEach(x=>x.onclick=async()=>{let m=item(x.dataset.share);if(navigator.share)await navigator.share({title:m.title,text:'Confira no ONIX',url:location.href});else{await navigator.clipboard?.writeText(location.href);alert('Link copiado')}});document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>{S.cat=x.dataset.cat;S.page='movies';render()});document.querySelector('#cat')?.addEventListener('change',e=>{S.cat=e.target.value;render()});document.querySelector('#q')?.addEventListener('input',e=>{S.q=e.target.value;render();document.querySelector('#q')?.focus()})}
render();